spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Tech_Gadgets_Store_Project
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
tax:
  api:
    url: https://teapi.netlify.app/api/statetax